# Prometheus配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'image-processor'
    environment: 'production'

# 告警规则文件
rule_files:
  - 'alerts.yml'

# 抓取配置
scrape_configs:
  # 后端服务监控
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/api/performance/metrics'
    scrape_interval: 30s

  # AI服务监控
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Docker容器监控
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
